// AUTO-GENERATED — NE PAS MODIFIER MANUELLEMENT
// Genere par scripts/sync-client.ts depuis CLIENT.md
// Pour modifier: editer CLIENT.md puis lancer npm run sync-client

export const clientConfig = {
  NOM_ENTREPRISE: "Nom de l'Entreprise",
  NOM_LEGAL: "Nom de l'Entreprise SARL",
  SIRET: "000 000 000 00000",
  METIER: "couvreur",
  METIER_LABEL: "Couvreur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "Prenom",
  NOM_DIRIGEANT: "Nom",
  DIPLOME_DIRIGEANT: "artisan couvreur diplome",
  ANNEE_CREATION: "2010",
  ANNEES_EXPERIENCE: "15",
  TELEPHONE: "00 00 00 00 00",
  EMAIL: "contact@votre-domaine.fr",
  ADRESSE: "1 Rue de la Paix",
  CODE_POSTAL: "00000",
  VILLE: "Votre Ville",
  DEPARTEMENT: "Votre Departement",
  REGION: "Votre Region",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 8h00-18h00, Sam: 9h00-13h00",
  ZONE_INTERVENTION: "Votre ville et region",
  LATITUDE: "46.603354",
  LONGITUDE: "1.888334",
  COULEUR_PRIMAIRE_HUE: "220",
  COULEUR_PRIMAIRE_900: "oklch(0.22 0.06 220)",
  COULEUR_ACCENT_HUE: "25",
  COULEUR_ACCENT_500: "oklch(0.64 0.16 25)",
  COULEUR_FOND_50: "oklch(0.985 0.005 80)",
  FONT_TITRES: "Playfair Display",
  FONT_CORPS: "DM Sans",
  DOMAINE: "www.votre-domaine.fr",
  META_TITLE: "Nom de l'Entreprise | Couvreur a Votre Ville",
  META_DESCRIPTION: "Couvreur a Votre Ville. Couverture, renovation de toiture, zinguerie, isolation, depannage urgence. Devis gratuit.",
  META_KEYWORDS: "couvreur, toiture, couverture, renovation toiture, zinguerie, isolation toiture, depannage toiture, couvreur professionnel",
  SCHEMA_TYPE: "RoofingContractor",
  SLOGAN: "Votre Slogan Ici",
  ACCROCHE_HERO: "Votre Toiture — Entre de Bonnes Mains",
  DESCRIPTION_ENTREPRISE: "Votre description d'entreprise. Couverture, renovation, zinguerie et isolation — un savoir-faire artisanal au service de votre toiture.",
  DESCRIPTION_FOOTER: "Votre description courte pour le footer du site.",
  DESCRIPTION_APROPOS: "Fondee par Prenom Nom, votre entreprise est nee d'une passion profonde pour le metier de couvreur et le travail bien fait.",
  SERVICE_1_TITRE: "Couverture Neuve",
  SERVICE_1_DESC: "Installation complete de votre toiture neuve en ardoise, tuiles, zinc ou bac acier, dans les regles de l'art.",
  SERVICE_2_TITRE: "Renovation de Toiture",
  SERVICE_2_DESC: "Diagnostic complet et renovation de votre couverture existante pour retrouver etancheite et esthetique.",
  SERVICE_3_TITRE: "Zinguerie",
  SERVICE_3_DESC: "Pose et reparation de gouttieres, cheneaux, descentes EP, noues et solins en zinc, cuivre ou aluminium.",
  SERVICE_4_TITRE: "Isolation de Toiture",
  SERVICE_4_DESC: "Isolation par l'interieur ou l'exterieur (sarking) pour reduire vos deperditions thermiques jusqu'a 30%.",
  SERVICE_5_TITRE: "Depannage & Urgence",
  SERVICE_5_DESC: "Intervention rapide sous 24 a 48h pour fuites, tuiles arrachees et degats de tempete. Bachage d'urgence.",
  SERVICE_6_TITRE: "Demoussage & Entretien",
  SERVICE_6_DESC: "Demoussage, traitement anti-mousse et hydrofuge pour prolonger la duree de vie de votre couverture.",
  GOOGLE_MAPS_URL: "",
  GOOGLE_REVIEWS_URL: "",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  LINKEDIN_URL: "",
  PINTEREST_URL: "",
  TEMOIGNAGE_1_NOM: "Client Satisfait",
  TEMOIGNAGE_1_VILLE: "Votre Ville",
  TEMOIGNAGE_1_TEXTE: "Nom de l'Entreprise a realise la renovation complete de notre toiture en ardoise. Travail soigne, equipe ponctuelle et professionnelle. Resultat impeccable !",
  TEMOIGNAGE_1_NOTE: "5",
  TEMOIGNAGE_2_NOM: "Famille Dupont",
  TEMOIGNAGE_2_VILLE: "Commune voisine",
  TEMOIGNAGE_2_TEXTE: "Isolation de notre toiture par sarking realisee dans les regles de l'art. Nous avons deja constate une nette amelioration du confort thermique. Merci !",
  TEMOIGNAGE_2_NOTE: "5",
  TEMOIGNAGE_3_NOM: "M. Durant",
  TEMOIGNAGE_3_VILLE: "Ville proche",
  TEMOIGNAGE_3_TEXTE: "Intervention rapide apres une tempete pour bachage et reparation. Equipe reactive et travail de qualite. Je recommande vivement.",
  TEMOIGNAGE_3_NOTE: "5",
  HEBERGEUR_NOM: "Vercel Inc.",
  HEBERGEUR_ADRESSE: "340 Pine Street, Suite 701, San Francisco, CA 94104, USA",
  HEBERGEUR_SITE: "vercel.com",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
  PACK_PHOTOS_METIER: "couvreur",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
